spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202001c
    username: postgres
    password: postgres
  
  mail:    host: smtp.gmail.com
    port: 587
    username: rakuraku.coffee.202001c@gmail.com
    password: kmgmmnavsbdkcqrn
